replicaCount: 1

image:
  repository: ghost
  tag: "5.71.0-alpine"

ingress:
  enabled: true
  className: "nginx"
  host: "my-ghost-blog.local"

mariadb:
  auth:
    rootPassword: "secret-root-password"
    database: "ghost_db"
    username: "ghost_user"
    password: "ghost_password"
  primary:
    persistence:
      enabled: false
