apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ghost
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: "http://{{ .Values.ingress.host }}"
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: "{{ .Release.Name }}-mariadb"
        - name: database__connection__user
          value: "{{ .Values.mariadb.auth.username }}"
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mariadb
              key: mariadb-password
        - name: database__connection__database
          value: "{{ .Values.mariadb.auth.database }}"
